# Generated by Django 5.0.6 on 2026-03-12 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the API consumer (e.g., 'Mobile App', 'Web Client')", max_length=100, unique=True)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of API key usage')),
                ('is_active', models.BooleanField(default=True)),
                ('can_generate_layouts', models.BooleanField(default=True)),
                ('can_list_layouts', models.BooleanField(default=True)),
                ('can_access_exports', models.BooleanField(default=True)),
                ('max_requests_per_day', models.IntegerField(blank=True, default=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='AIProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('background_removal', 'Background Removal'), ('product_detection', 'Product Detection'), ('design_placement', 'Design Placement'), ('realistic_blending', 'Realistic Blending'), ('complete_processing', 'Complete AI Processing')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('input_image', models.FileField(upload_to='ai_processing/input/')),
                ('output_image', models.FileField(blank=True, null=True, upload_to='ai_processing/output/')),
                ('parameters', models.JSONField(default=dict, help_text='Processing parameters (blend mode, opacity, etc.)')),
                ('result_data', models.JSONField(default=dict, help_text='Processing results (detected products, confidence, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='api.apikey')),
            ],
            options={
                'verbose_name': 'AI Processing Job',
                'verbose_name_plural': 'AI Processing Jobs',
                'db_table': 'ai_processing_jobs',
            },
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('status_code', models.IntegerField(default=200)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('request_size_bytes', models.IntegerField(blank=True, default=0, null=True)),
                ('response_size_bytes', models.IntegerField(blank=True, default=0, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.apikey')),
            ],
            options={
                'verbose_name': 'API Request',
                'verbose_name_plural': 'API Requests',
                'db_table': 'api_requests',
            },
        ),
        migrations.CreateModel(
            name='ExportedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=255)),
                ('export_file_path', models.CharField(db_index=True, max_length=500)),
                ('input_files', models.JSONField(default=list, help_text='List of input file paths')),
                ('generation_time_ms', models.IntegerField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='api.apikey')),
            ],
            options={
                'verbose_name': 'Exported Result',
                'verbose_name_plural': 'Exported Results',
                'db_table': 'exported_results',
            },
        ),
        migrations.CreateModel(
            name='ModelCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('load_time', models.FloatField(help_text='Time to load model in seconds')),
                ('memory_usage', models.BigIntegerField(help_text='Memory usage in bytes')),
                ('is_gpu_compatible', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('loading', 'Loading'), ('error', 'Error'), ('disabled', 'Disabled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Cache Entry',
                'verbose_name_plural': 'Model Cache Entries',
                'db_table': 'model_cache',
                'indexes': [models.Index(fields=['model_name'], name='model_cache_model_n_8092c5_idx'), models.Index(fields=['status'], name='model_cache_status_9d89af_idx'), models.Index(fields=['last_used'], name='model_cache_last_us_195b53_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_type', models.CharField(default='image', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='File will be auto-deleted after this date', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='api.apikey')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'db_table': 'uploaded_files',
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='api_keys_key_291dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active'], name='api_keys_is_acti_73be43_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['last_used_at'], name='api_keys_last_us_fbf652_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['api_key', 'created_at'], name='ai_processi_api_key_e0b618_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['job_type', 'status'], name='ai_processi_job_typ_306e78_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='ai_processi_status_aa4b18_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['api_key', 'created_at'], name='api_request_api_key_dd9736_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['endpoint', 'created_at'], name='api_request_endpoin_30f05a_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['status_code'], name='api_request_status__f5b5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='exportedresult',
            index=models.Index(fields=['api_key', 'created_at'], name='exported_re_api_key_6eabb5_idx'),
        ),
        migrations.AddIndex(
            model_name='exportedresult',
            index=models.Index(fields=['layout_name'], name='exported_re_layout__021b64_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['api_key', 'created_at'], name='uploaded_fi_api_key_def084_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['expires_at'], name='uploaded_fi_expires_8df13c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['is_deleted'], name='uploaded_fi_is_dele_45ff28_idx'),
        ),
    ]
