# Generated by Django 5.0.6 on 2026-04-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasdata',
            name='callback_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
