# Generated by Django 5.0.6 on 2026-03-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='is_ops_team',
            field=models.BooleanField(default=False, help_text='Whether this key belongs to the internal operations team'),
        ),
    ]
