# Generated by Django 5.0.6 on 2026-03-30 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_embedsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='embedsession',
            new_name='embed_sessi_token_0e7d0a_idx',
            old_name='embed_sessions_token_idx',
        ),
        migrations.RenameIndex(
            model_name='embedsession',
            new_name='embed_sessi_expires_b9a39e_idx',
            old_name='embed_sessions_expires_idx',
        ),
        migrations.AlterField(
            model_name='embedsession',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
