# Generated by Django 5.0.6 on 2026-07-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_canvasdata_render_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='renderjob',
            name='render_jobs_celery__8d3cd8_idx',
        ),
        migrations.RenameIndex(
            model_name='exportedresult',
            new_name='exported_re_is_dele_c59037_idx',
            old_name='exported_results_is_del_ctd_idx',
        ),
        migrations.AlterField(
            model_name='canvasdata',
            name='callback_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='canvasdata',
            name='editor_state',
            field=models.JSONField(blank=True, help_text='Full editor state JSON (frames, overlays, colours, surfaces).', null=True),
        ),
        migrations.AddIndex(
            model_name='renderjob',
            index=models.Index(fields=['queue_name', 'status', 'created_at'], name='render_jobs_queue_n_c9cfcf_idx'),
        ),
        migrations.AddIndex(
            model_name='renderjob',
            index=models.Index(fields=['status', 'completed_at'], name='render_jobs_status_75d827_idx'),
        ),
    ]
