# Generated by Django 5.0.6 on 2026-09-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_import_prod_layouts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='layoutcatalogue',
            new_name='layout_cata_name_8d435b_idx',
            old_name='layout_catalogue_name_idx',
        ),
        migrations.RenameIndex(
            model_name='layoutcatalogue',
            new_name='layout_cata_product_e54c57_idx',
            old_name='layout_catalogue_pt_dep_idx',
        ),
        migrations.RenameIndex(
            model_name='layoutcatalogue',
            new_name='layout_cata_categor_c2fecf_idx',
            old_name='layout_catalogue_category_idx',
        ),
        migrations.RenameIndex(
            model_name='layoutcatalogue',
            new_name='layout_cata_is_depr_4f0a88_idx',
            old_name='layout_catalogue_dep_pub_idx',
        ),
    ]
