# Generated by Django 5.0.6 on 2026-09-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_layout_catalogue_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutcatalogue',
            name='renamed_to',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Set on the OLD row when an ops rename supersedes it. Lets a "
                    "caller still holding the pre-rename name (e.g. a partner's "
                    "hardcoded embed URL) keep resolving via resolve_active() "
                    "instead of 404ing the moment this row is deprecated."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='renamed_from',
                to='api.layoutcatalogue',
                to_field='name',
            ),
        ),
    ]
