# Generated by Django 5.0.6 on 2026-09-16

import re

from django.db import migrations, models


def _default_display_name(name):
    """Local copy of api.models.default_display_name_for — migrations must not
    import the live model module, since its shape can change out from under
    an old migration. Keep this in sync with that function and with
    formatLayoutDisplayName() in frontend/nextjs/.../editor/layout/[name]/page.tsx."""
    words = re.sub(r'_+', ' ', name or '').strip().split()
    return ' '.join(w[:1].upper() + w[1:] for w in words)


def backfill_display_names(apps, schema_editor):
    LayoutCatalogue = apps.get_model('api', 'LayoutCatalogue')
    for layout in LayoutCatalogue.objects.all():
        if not layout.display_name:
            layout.display_name = _default_display_name(layout.name)
            layout.save(update_fields=['display_name'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_layoutcatalogue_renamed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutcatalogue',
            name='display_name',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    "Ops-editable customer-facing name, independent of `name`. Freely "
                    "editable at any time, unlike the identifier. Blank means no one has "
                    "set one yet — callers should fall back to default_display_name_for(name)."
                ),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='layoutcatalogue',
            name='name',
            field=models.CharField(
                db_index=True,
                help_text=(
                    "Layout identifier (e.g., 'circle_48mm'). Case-sensitive. "
                    "Immutable once the row exists — see save()."
                ),
                max_length=255,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_display_names, noop_reverse),
    ]
